# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
paginate: 10
paginate_path: "blog/page:num"
# Permalinks
permalink: pretty

# Build settings
markdown: kramdown

# Your disqus shortname, entering this will enable commenting on posts
disqus: "alexkilty"

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: "UA-54952727-1"
